apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: mysql-pass
  literals:
  - password=test123
- name: mysql-user
  literals:
  - username=userwp
- name: mysql-user-password
  literals:
  - passworduser=Mysql.User2024@
- name: mysql-database
  literals:
  - database=multitenant_wp
resources: 
  - storage-class.yaml
  - mysql-deployment.yaml
  - mysql-storage.yaml
  - wp-deployment.yaml
  - wp-storage.yaml
