apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata: 
  name: wp-test-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: adrephos@gmail.com
    privateKeySecretRef:
      name: letsencrypt-test
    solvers:
      - http01:
          ingress:
            class: nginx
